name: Exploring Variables and Secrets

#ON the job LEVEL !!

on: 
    push
jobs:
    docker:
        env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: ahmad
                IMAGE_NAME: github-actions-nginx
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
            - name: Docker login
              env:
                DOCKER_PASSWORD: aseadsdaedf
              run: echo docker login --username=$DOCKER_USERNAME--password=$DOCKER_PASSWORD
            
            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

              
    deploy:
        env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: ahmad
                IMAGE_NAME: github-actions-nginx
        needs: docker
        runs-on: ubuntu-latest
        steps:
          - name: Docker Run
            run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


              